apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kube-system
  name: metrics-server-rolebinding
subjects:
- kind: ServiceAccount
  name: metrics-server
  namespace: kube-system
roleRef:
  kind: Role
  name: metrics-server-role
  apiGroup: rbac.authorization.k8s.io
