apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  project: baseline
  destination:
    namespace: ""
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/nickkostov/argocd/
    path: overlay/docker-desktop/baseline/metrics-server/chart
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      